@url_base=http://localhost:3000
@path=users

# User data
@user_name=Maria
@user_email=maria@teste.com
@user_password=1234
@user_admin=true

### Create user admin
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "{{user_name}}",
  "email": "{{user_email}}",
  "password": "{{user_password}}",
  "admin": {{user_admin}}
}

### Create user not admin
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "{{user_name}}",
  "email": "{{user_email}}",
  "password": "{{user_password}}"
}

### Create user with same email -> "error": "User already exists!"
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "{{user_name}}",
  "email": "{{user_email}}",
  "password": "{{user_password}}",
  "admin": {{user_admin}}
}

### Create user without email -> "error": "Incorrect email!"
POST {{url_base}}/{{path}}
Content-Type: application/json

{
  "name": "{{user_name}}",
  "password": "{{user_password}}",
  "admin": {{user_admin}}
}
